#!/bin/sh

set -e

if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
    . /usr/share/apache2/apache2-maintscript-helper

    php5_enable() {
	mpm=$(a2query -M)
	case "$(a2query -M)" in
	    prefork|itk) return 0;;
	    *) if apache2_switch_mpm prefork; then return 0; fi;;
	esac
        apache2_msg err "Could not switch to prefork MPM, not enabling php5"
	return 1
    }

else
    echo "Warning: Could not load Apache 2.4 maintainer script helper."

    php5_enable() {
        return 1;
    }

fi

# we've registered a trigger to handle extension updates.
if [ "$1" = "triggered" ] && [ "$2" = "/etc/php5/apache2/conf.d" ]; then
    if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
	. /usr/share/apache2/apache2-maintscript-helper
	apache2_reload restart
    fi
    exit 0
elif [ "$1" != "configure" ]; then
    exit 0
fi

CONFDIR=/etc/php5/apache2filter/conf.d

if [ -L $CONFDIR ]; then
    rm $CONFDIR
    mkdir $CONFDIR
fi

if [ "$1" = "configure" ]; then
    phpini="/etc/php5/apache2filter/php.ini"

    if [ "apache2filter" = "cli" ]; then
	ucf /usr/share/php5/php.ini-production.apache2filter $phpini
    else
	ucf /usr/share/php5/php.ini-production $phpini
    fi
    ucfr libapache2-mod-php5filter $phpini

    if [ -e /usr/share/php5/php5-maintscript-helper ]; then
	. /usr/share/php5/php5-maintscript-helper
	
	mods=$(php5query -M)
	for mod in $mods; do
	    php5_invoke enmod apache2filter $mod
	done
    fi

fi

# Automatically added by dh_apache2
if php5_enable; then
	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		. /usr/share/apache2/apache2-maintscript-helper
		for conf in php5filter  ; do
			apache2_invoke enmod $conf  || exit $?
		done
	fi
fi
# End automatically added section


exit 0
