#! /bin/sh

set -e

# conffiles must be moved before invoking rc.d
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/apache2/conf.d/apache2-doc /etc/apache2/conf-available/apache2-doc.conf -- "$@"
# End automatically added section


# This code should use dh_apache2 once it is available as build dependency

if [ "$1" = "configure" ] ; then
	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		. /usr/share/apache2/apache2-maintscript-helper
		apache2_invoke enconf apache2-doc || true
	fi
fi

exit
