#!/bin/sh
set -e



case "$1" in
    configure)

	# Only activate jk if this is not an upgrade
	if [ -z "$2" ]; then
	    a2enmod jk || true
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
	echo "$0 called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

exit 0
