#!/bin/sh
set -e

CERTDIR=/etc/apache2/nssdb

if [ "$1" = purge ]; then
    for i in cert8.db key3.db install.log secmod.db; do
        rm -f $CERTDIR/$i
    done
    echo "libapache2-mod-nss certificate database cleared."
fi

# Automatically added by dh_apache2
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in nss  ; do
				apache2_invoke dismod $conf  || exit $?
			done
		fi
	fi
fi
# End automatically added section


