#!/bin/sh

set -e

case "$1" in
  configure)
    if [ -z "$2" ]
    then
      a2enmod bw || true
    fi
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac



exit 0
