#!/bin/sh

set -e

case "$1" in
    remove)
	test -e /etc/apache2/mods-enabled/fcgid.load && a2dismod fcgid
    ;;
    upgrade|deconfigure|failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac




exit 0
